version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "3000:3000"
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      restart_policy:
          condition: on-failure
          delay: 1s
          max_attempts: 3
          window: 120s
volumes:
     pgdata: