version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: train_spammer
      POSTGRES_USER: svyatoslav
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db