version: '3'

services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5433"
  app:
    build: .
    environment:
    - TZ=Europe/Moscow
    env_file:
      - .env
    depends_on:
      - db
    deploy:
      restart_policy:
          condition: on-failure
          max_attempts: 3
volumes:
     pgdata: