version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:5432"
  app:
    build: .
    environment:
    - TZ=Europe/Moscow
    env_file:
      - .env.docker
    depends_on:
      - db
    deploy:
      restart_policy:
          condition: on-failure
          max_attempts: 3
volumes:
     pgdata: